[phases.setup]
nixpkgs = ["python312", "python312Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r c-Users-Admin-code-stock-wars/requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "cd c-Users-Admin-code-stock-wars && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
