[phases.setup]
nixpkgs = ["python312", "python312Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
